### ISSUE TITLE
semantic APIs

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#436]
v1.0 supports inspections of the structure of Scala code (syntax and tokens), but it doesn't provide any facilities to inspect semantics (what's the type of this fragment of code? what does this name point to? etc). We had this in scala.reflect, and we need to have this in scala.meta, too, because that's one of the most basic features one expects in a metaprogramming framework.

Prior to the 0.1.0-RCx cleanup, we used to have a prototype interface and implementation of semantic APIs. I removed them, because the quality of their implementation wasn't high enough to be part of what was supposed to become v1.0. That'll be a good place to start: https://github.com/scalameta/scalameta/tree/763e3318e0816d3b692b57a03c2b2e0040a403d4.

Our latest attempt at the user <-> meta semantic API is archived at https://github.com/scalameta/scalameta/blob/763e3318e0816d3b692b57a03c2b2e0040a403d4/scalameta/semantic/src/main/scala/scala/meta/semantic/Api.scala. The most recent version of the meta <-> platform semantic API is archived at https://github.com/scalameta/scalameta/blob/763e3318e0816d3b692b57a03c2b2e0040a403d4/scalameta/semantic/src/main/scala/scala/meta/semantic/Context.scala. The biggest chunk of work is to provide the implementation of the meta <-> platform part.

Blockers:
- [x] #144 (Finish semantic model)
- [ ] #146 (Denotations are too precise)
- [ ] #286 (Think about how repeated typechecks should work)
- [ ] #148 (scala.reflect -> scala.meta tree converter)
- [ ] #433 (classpath -> scala.meta converter)

**Comment by xeno-by** [comment]
Superseded by https://github.com/scalameta/scalameta/issues/604.
