### ISSUE TITLE
Offline mirror with support for Ref.symbol

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#607]
**DISCLAIMER:** `Ref.symbol` is only going to be available in `scala.meta.semantic.v1`. The concept of symbols has a benefit of being easy to implement, but has a bunch of known issues discovered in the scala.reflect experiment. Therefore, in `scala.meta.semantic.v2`, we're planning to remove symbols and `Ref.symbol` and replace them with something else (#610).

------------

Prerequisites:
  - [x] Online mirror with support for Ref.symbol (#606)

In this ticket, we'll be implementing persistence for our semantic db (#605), and a mirror that can load previously persisted databases. Much like the mirror from #606, this mirror will only support one semantic API, `Ref.symbol`, but in a different way, by:
  * Taking a classpath that contains one or more persisted databases and a sourcepath that contains sources referred to in those databases
  * Loading persisted databases and merging them into one semantic database 
  * Using the semantic db and just the semantic db to reply to semantic queries.

Usage example:
```scala
implicit val m = Mirror("<classpath>", "<sourcepath>")
// the same as in #606
```

Implementation plan:
  - [ ] Specify persistence format for semantic databases in #605 
    * @densh suggested that we persist semantic databases on per-classfile basis, similarly to sjsir and nir files from Scala.js and Scala Native. Otherwise, incremental compilation may be problematic.
    * @stuhood suggested that we'll need to integrate with sbt to have incremental compilation working correctly in all cases: https://github.com/sbt/zinc/issues/125.
  - [ ] Update the `Location.uri` specification in #605 to make sure we can correlate locations used to create semantic dbs and locations coming from sourcepaths when loading them
  - [x] Implement semantic persistence by hijacking the scalac backend similarly to [our previous approaches at TASTY support](https://github.com/scalameta/scalameta/blob/7d6f917de39f8bfdbeb1f87d145f9797803d9ebb/scalahost/src/main/scala/scala/meta/internal/hosts/scalac/HijackBackend.scala).
  - [x] Create a classpath/sourcepath-based implementation of `Mirror`
  - [x] Add testing infrastructure

**Comment by xeno-by** [comment]
Implemented an initial version of semantic DB persistence in 7c44e77. The format is an extremely inefficient text-based representation, locations are still specified via absolute paths. Nonetheless, the functionality is already useful. I'm closing this issue, moving further discussion to #605.

**Comment by jvican** [comment]
I see you mention https://github.com/sbt/zinc/issues/125. I'd like to see what we can do in the Zinc front to make the Scala Meta semantic database compatible with it. I have no idea how your text-based representation works, so perhaps we can work out the requirement/details to fix this issue down the line.
