### ISSUE TITLE
Ref.symbol for unattributed trees

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#608]
**DISCLAIMER:** `Ref.symbol` is only going to be available in `scala.meta.semantic.v1`. The concept of symbols has a benefit of being easy to implement, but has a bunch of known issues discovered in the scala.reflect experiment. Therefore, in `scala.meta.semantic.v2`, we're planning to remove symbols and `Ref.symbol` and replace them with something else (#610).

------------

Prerequisites:
  - [x] Online mirror with support for Ref.symbol (#606)

The next step after supporting attributed trees in #606 and #607 is implementing `Ref.symbol` for unattributed trees. We'd like to shield the user from understanding the distinction between unattributed and attributed trees, so we'll perform typechecking under the covers.

Usage example:
```scala
implicit val m = Mirror(...)
t"Int".symbol // _root_.scala.Int#
q"implicitly".symbol // _root_.scala.Predef.implicitly(Ljava/lang/Object;)Ljava/lang/Object;.
```

Implementation plan:
  - [ ] Track positions for quasiquotes, so that we have easy locations for things like `t"Int"` (#46, #159 and #510 will likely be relevant)
  - [x] Implement on-the-fly typechecking for unattributed trees
    * Simple quasiquotes should be easy, because they should have positions by now
    * Dynamically parsed strings should be easy as well by the same reasoning
    * Unattributed trees created manually or thrown together via unquoting/splicing will probably be hard, but we should try to support them too
    * Reject mixed unattributed/attributed trees crashing with an error message referring to #621
  - [x] Some previous work in this domain:
    * https://github.com/scalameta/scalameta/blob/7d6f917de39f8bfdbeb1f87d145f9797803d9ebb/scalahost/src/main/scala/scala/meta/internal/hosts/scalac/contexts/Adapter.scala#L54
    * Think whether #286 applies here
  - [x] Upgrade implementations of #606 and #607 to use on-the-fly typechecking in cases when there's a semantic db miss

**Comment by xeno-by** [comment]
I didn't need to implement position tracking for quasiquotes in order to hack up this functionality. For unpositioned trees, I'm simply prettyprinting and then immediately reparsing, obtaining a structurally-equivalent, but now well-positioned tree. Seems to work well for the original use cases of `t"Int"` or `q"List"`. Closing this issue and leaving the rest for #621.

**Comment by xeno-by** [comment]
As described in #808, we're giving up on runtime typechecking. As a result, this API becomes impossible to implement, so #808 removes it.
