### ISSUE TITLE
Term.tpe

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#611]
Prerequisites:
  - [x] Online mirror with support for Ref.symbol (#606)

Following `Ref.symbol` (#606, #607, #608) and other symbol APIs (#609), we'd also like to support `Term.tpe` that returns a type of a given term in Scala source code.

Usage example:
```scala
implicit val m = Mirror(...)
q"List(1, 2, 3)".tpe // t"Int"
```

Implementation plan:
  - [ ] Upgrade the specification of semantic database (#605) to include support for types
  - [ ] Add support for types to the `CompilationUnit => Database` functionality. I suspect that we may have to be very mindful of performance here, since the number of terms greatly exceeds the number of names.
  - [ ] Add support for types in the semantic db persistence functionality
  - [ ] Figure out which scala.reflect types we want to support. See #273 for relevant discussion.
  - [ ] Add a converter that goes from scala.reflect types to scala.meta types. Unlike with symbols, here we won't be able to get away with just strings.

**Comment by xeno-by** [comment]
Recently, we decided to limit the surface of our work to actionable items only - either bugs in existing code or feature requests that are warranted by the roadmap. 

While semantic API is definitely on our roadmap, we're going to figure out desired APIs from use cases, not from reflecting on scala.reflect and pondering what functionality from there we should add to Scalameta. That's why I'll be closing this issue and letting feature requests be submitted naturally by our users.

**Comment by xeno-by** [comment]
Superseded by https://github.com/scalameta/scalameta/issues/1212.
